### ISSUE TITLE
Suggestion: Configure synapse to use external Postgres on other VM.

### ISSUE THREAD

**Issue by mcarroll76** [ptman/matrix-docs#1]
As the article makes clear, the biggest limiting factor here is RAM. Given that the Oracle free offering includes two VMs, it seems logical to split the services between them. I'm not entirely sure how the RAM usage of the various services breaks down, but the most obvious and easy start towards this would be to host the database on the other VM. Would also relieve some CPU load.

**Comment by ptman** [comment]
That is a good suggestion, but I'm also trying to keep the howto short in order to keep it simple and hopefully more approachable to less technical users. And I think the playbook used doesn't support multi-host split (homeserver vs db server). I'll have to thing about this a bit. Thanks for the input!

**Comment by mcarroll76** [comment]
It won't set-up the separate DB server for you, but it can be configured to use an external Postgres easily enough:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-external-postgres.md

You could use a standard Ubuntu server image to set-up the DB server VM. Postgres is one of the standard package tasks available during the install procedure:

https://help.ubuntu.com/lts/serverguide/installing-from-cd.html

**Comment by ptman** [comment]
@Degenerate76 have you tried the oracle cloud that is assumed in the guide? There's no installing from CD

**Comment by mcarroll76** [comment]
I haven't tried i yet, but I would have assumed that they have a range of standard installation images like other services. Do they not have an Ubuntu image with standard Ubuntu install options?

Edit: OK, I found the list of standard images here:
https://docs.cloud.oracle.com/iaas/Content/Compute/References/images.html
I gather that these are "preinstalled" vdisk images with a bootable system, rather than install CD iso images that would go through an install procedure to put the OS on the vdisk.

So, starting with an Ubuntu minimal image, removing unnecessary stuff (following your previous instructions for the other VM), then "sudo apt install postgresql-server" should do the trick.

Could also use Docker, of course, but I don't think the weight of it would add any value for a single  purpose DB server VM. The Ubuntu bionic package of Postgres is at version 10, Synapse is known to work fine at 9.5+, so there shouldn't be any compatibility issues.
